name: su_gym
description: "A Flutter application for gym management and fitness tracking."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # UI related packages
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  qr_flutter: ^4.1.0
  intl: ^0.19.0
  
  # Firebase related packages
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.5
  firebase_analytics: ^10.8.5
  firebase_messaging: ^14.7.15
  flutter_local_notifications: ^16.3.0
  
  # State management
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  
  # Utilities
  http: ^1.2.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  url_launcher: ^6.2.4
  permission_handler: ^11.2.1
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Testing libraries
  mockito: ^5.4.4
  mocktail: ^1.0.3
  fake_cloud_firestore: ^2.4.8
  firebase_auth_mocks: ^0.13.0
  
  # Build tools
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

# Flutter configuration
flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    
  # Fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
          
# Icon configuration          
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  
# Splash screen configuration
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/splash_logo.png"
  android: true
  ios: true